name: Create Registry Publish PR by manual trigger (for testing)

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Comfy CustomNode Repo to setup ./pyproject.toml + .github/workflow/publish.yaml"
        required: true
        type: string
        default: "https://github.com/snomiao/ComfyNode-Registry-test"
jobs:
  run_comfy_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # setup hanzo-cli
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python -m pip install --upgrade pip
      - run: python -m venv .venv
      - run: source .venv/bin/activate
      - run: pip install hanzo-cli
      # Setup SSH Key for git push
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Setup Bun
      - run: pip install setuptools
      - uses: oven-sh/setup-bun@v2
      # Run Comfy-PR Worker
      - run: bun i
      - run: bun src/createComfyRegistryPullRequests.ts ${{ inputs.repo_url }}
        env:
          COMFY_PR_REPO: ${{ secrets.COMFY_PR_REPO }}
          FORK_OWNER: "ComfyNodePRs"
          FORK_PREFIX: "PR-"
          GH_TOKEN_COMFY_PR: ${{ secrets.GH_TOKEN_COMFY_PR }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          AUTH_GCLOUD_URL: https://comfy-pr.vercel.app
