name: gh-design
on:
  # schedule:
  #   # Runs every 5 minutes
  #   - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - sno-design-label-track
    paths:
      - ".github/workflows/gh-design.yaml"
      
      - "app/tasks/gh-design/gh-design.ts"
jobs:
  run_design_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # Run Design Label Scanner
      - run: bun i
      # debug token
      - run: bun src/slack/index.ts
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - run: bun app/tasks/gh-design/gh-design.ts
        env:
          COMFY_PR_REPO: ${{ secrets.COMFY_PR_REPO }}
          FORK_OWNER: "ComfyNodePRs"
          FORK_PREFIX: "PR-"
          GH_TOKEN_COMFY_PR: ${{ secrets.GH_TOKEN_COMFY_PR }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}